import type { Locale } from '../../domain/types';

export type BuilderTab = 'data' | 'checklist' | 'export' | 'import';

export interface TourStep {
  id: TourStepId;
  /** CSS selector list; the first visible match is highlighted. No target = centered card. */
  target?: string;
  /** Builder tab that must be active for this step. */
  tab?: BuilderTab;
  /** Primi panel state required by this step. */
  assistant?: 'open' | 'closed';
}

export type TourStepId =
  | 'welcome' | 'project' | 'model' | 'identification' | 'removed' | 'screening' | 'eligibility' | 'reasons'
  | 'inclusion' | 'diagram' | 'node' | 'validation' | 'toolbar' | 'checklist' | 'export' | 'primi'
  | 'primiSetup' | 'primiFill' | 'projects' | 'finish';

/** The journey: set up the project, fill the flow top to bottom, review, report, then Primi. */
export const tourSteps: TourStep[] = [
  { id: 'welcome', tab: 'data', assistant: 'closed' },
  { id: 'project', target: '.project-setup', tab: 'data' },
  { id: 'model', target: '#model-fieldset', tab: 'data' },
  { id: 'identification', target: '#section-identification', tab: 'data' },
  { id: 'removed', target: '#section-removed', tab: 'data' },
  { id: 'screening', target: '#section-screening', tab: 'data' },
  { id: 'eligibility', target: '#section-eligibility', tab: 'data' },
  { id: 'reasons', target: '.reasons-editor', tab: 'data' },
  { id: 'inclusion', target: '#section-sectionInclusion', tab: 'data' },
  { id: 'diagram', target: '.diagram-panel', tab: 'data' },
  { id: 'node', target: '.selected-node', tab: 'data' },
  { id: 'validation', target: '.validation-panel', tab: 'data' },
  { id: 'toolbar', target: '.builder-toolbar', tab: 'data' },
  { id: 'checklist', target: '.checklist-module', tab: 'checklist' },
  { id: 'export', target: '.export-panel', tab: 'export' },
  { id: 'primi', target: '.assistant-fab', tab: 'data', assistant: 'closed' },
  { id: 'primiSetup', target: '.assistant-panel', tab: 'data', assistant: 'open' },
  { id: 'primiFill', target: '.assistant-panel', tab: 'data', assistant: 'open' },
  { id: 'projects', target: '.desktop-nav a[href="/projects"], .mobile-menu > summary', tab: 'data', assistant: 'closed' },
  { id: 'finish', tab: 'data', assistant: 'closed' },
];

type StepText = Record<TourStepId, [title: string, body: string]>;

export const tourText: Record<Locale, StepText> = {
  'pt-BR': {
    welcome: ['Boas-vindas ao PRISMA Lab', 'Este tour mostra como montar um diagrama PRISMA 2020 do início ao fim — dos dados do projeto à exportação — e como o Primi, o assistente de IA, pode preencher os campos para você. Nada no seu projeto é alterado durante o tour.'],
    project: ['Identifique a revisão', 'Comece pelo título, autores, instituição e link do protocolo. Tudo é salvo automaticamente neste navegador — acompanhe o indicador “Salvo localmente” no topo.'],
    model: ['Escolha o modelo do fluxo', 'Revisão nova ou atualizada, com ou sem outras fontes: essas escolhas selecionam um dos quatro modelos oficiais do PRISMA 2020 e mostram só os campos que se aplicam.'],
    identification: ['Registre a identificação', 'Adicione cada base consultada (PubMed, Scopus…) com o número de registros; o total é somado automaticamente. Registros de ensaios e estudos têm campo próprio.'],
    removed: ['Remova antes da triagem', 'Informe as duplicatas e os registros removidos por ferramentas de automação ou por outros motivos antes da triagem.'],
    screening: ['Triagem e recuperação', 'Os registros triados são calculados (identificados − removidos). Você informa os excluídos na triagem e os relatos não recuperados; o app deriva o restante e mostra a fórmula de cada valor.'],
    eligibility: ['Avalie a elegibilidade', 'Informe quantos relatos foram excluídos após a leitura do texto completo. Os relatos avaliados vêm do cálculo anterior.'],
    reasons: ['Detalhe as razões de exclusão', 'Liste cada motivo com sua contagem. A soma precisa bater com o total de relatos excluídos — a validação avisa se não bater.'],
    inclusion: ['Feche com a inclusão', 'Informe os novos estudos incluídos. Relatos e totais são calculados, somando os estudos da versão anterior quando a revisão é atualizada.'],
    diagram: ['Acompanhe o diagrama ao vivo', 'O fluxograma se atualiza a cada número. Clique em uma caixa para editar o campo correspondente, alterne entre os estilos clássico e moderno e use o zoom.'],
    node: ['Veja a origem de cada valor', 'Aqui aparecem o valor, a origem (informado ou calculado) e a fórmula da caixa selecionada. Se precisar sobrescrever um cálculo, registre a justificativa; notas e proveniência ficam documentadas.'],
    validation: ['Corrija com a validação', 'Cada alerta explica o que aconteceu, por que importa e como resolver. Clique em um alerta para ir direto ao campo envolvido.'],
    toolbar: ['Use a barra de ferramentas', 'Desfazer e refazer, zoom, tela cheia, impressão, limpar os dados e carregar um exemplo didático — e reabrir este tour quando quiser.'],
    checklist: ['Complete o checklist', 'Acompanhe os 27 itens do PRISMA 2020: marque o status, anote seção e página do manuscrito e veja o progresso por seção.'],
    export: ['Exporte para publicação', 'Gere PDF e SVG vetoriais, PNG, HTML interativo, CSV/XLSX, relatório e um pacote ZIP. Salve também backups JSON do projeto.'],
    primi: ['Conheça o Primi', 'O Primi é o assistente de IA do PRISMA Lab: responde sobre o PRISMA 2020 e sobre os dados deste projeto. Abra-o por este botão.'],
    primiSetup: ['Conecte seu provedor de IA', 'Escolha entre 15 provedores — OpenAI, Anthropic, Gemini, DeepSeek, GLM, Qwen, Mistral e outros — ou um modelo local com Ollama, e use sua própria chave. Ela fica só neste navegador, e os dados vão direto ao provedor, com seu consentimento.'],
    primiFill: ['Deixe o Primi preencher', 'Escreva seus números, como “PubMed 320, Scopus 210, 85 duplicatas”. O Primi mostra um cartão com cada campo (atual → novo) e nada muda até você clicar em Aplicar; um Desfazer reverte tudo. Campos calculados seguem as fórmulas.'],
    projects: ['Gerencie seus projetos', 'Em Meus projetos você abre, duplica, renomeia, importa e exclui diagramas. Tudo fica neste navegador — faça backups regularmente.'],
    finish: ['Tudo pronto!', 'Você percorreu a jornada completa do PRISMA Lab. Reabra este tour quando quiser pelo botão Tour na barra de ferramentas.'],
  },
  en: {
    welcome: ['Welcome to PRISMA Lab', 'This tour shows how to build a PRISMA 2020 diagram from start to finish — from project data to export — and how Primi, the AI assistant, can fill in the fields for you. Nothing in your project changes during the tour.'],
    project: ['Identify the review', 'Start with the title, authors, institution and protocol link. Everything is saved automatically in this browser — watch the “Saved locally” indicator at the top.'],
    model: ['Choose the flow model', 'New or updated review, with or without other sources: these choices select one of the four official PRISMA 2020 templates and show only the fields that apply.'],
    identification: ['Record identification', 'Add each database you searched (PubMed, Scopus…) with its number of records; the total is summed automatically. Study and trial registers have their own field.'],
    removed: ['Remove before screening', 'Enter duplicates and records removed by automation tools or for other reasons before screening.'],
    screening: ['Screening and retrieval', 'Records screened are calculated (identified − removed). You enter records excluded at screening and reports not retrieved; the app derives the rest and shows each formula.'],
    eligibility: ['Assess eligibility', 'Enter how many reports were excluded after full-text reading. Reports assessed come from the previous calculation.'],
    reasons: ['Detail the exclusion reasons', 'List each reason with its count. The sum must match the total of excluded reports — validation warns you when it does not.'],
    inclusion: ['Close with inclusion', 'Enter the new studies included. Reports and totals are calculated, adding studies from the previous version for updated reviews.'],
    diagram: ['Watch the diagram live', 'The flowchart updates with every number. Click a box to edit its field, switch between the classic and modern styles, and use zoom.'],
    node: ['See where each value comes from', 'This shows the value, origin (entered or calculated) and formula of the selected box. To override a calculation, record a justification; notes and provenance stay documented.'],
    validation: ['Fix issues with validation', 'Each alert explains what happened, why it matters and how to fix it. Click an alert to jump straight to the field involved.'],
    toolbar: ['Use the toolbar', 'Undo and redo, zoom, full screen, print, clear the data and load a teaching example — and reopen this tour whenever you like.'],
    checklist: ['Complete the checklist', 'Track the 27 PRISMA 2020 items: set the status, note the manuscript section and page, and follow progress by section.'],
    export: ['Export for publication', 'Generate vector PDF and SVG, PNG, interactive HTML, CSV/XLSX, a report and a ZIP package. Also save JSON backups of the project.'],
    primi: ['Meet Primi', "Primi is PRISMA Lab's AI assistant: it answers questions about PRISMA 2020 and this project's data. Open it with this button."],
    primiSetup: ['Connect your AI provider', 'Choose among 15 providers — OpenAI, Anthropic, Gemini, DeepSeek, GLM, Qwen, Mistral and more — or a local model with Ollama, using your own key. The key stays in this browser and data goes straight to the provider, with your consent.'],
    primiFill: ['Let Primi fill it in', 'Type your numbers, e.g. “PubMed 320, Scopus 210, 85 duplicates”. Primi shows a card with each field (current → new) and nothing changes until you click Apply; one Undo reverts it all. Calculated fields keep their formulas.'],
    projects: ['Manage your projects', 'In My projects you open, duplicate, rename, import and delete diagrams. Everything stays in this browser — back up regularly.'],
    finish: ["You're all set!", 'You have walked through the whole PRISMA Lab journey. Reopen this tour any time with the Tour button in the toolbar.'],
  },
  it: {
    welcome: ['Benvenuto in PRISMA Lab', 'Questo tour mostra come costruire un diagramma PRISMA 2020 dall’inizio alla fine — dai dati del progetto all’esportazione — e come Primi, l’assistente IA, può compilare i campi per te. Durante il tour il progetto non viene modificato.'],
    project: ['Identifica la revisione', 'Inizia da titolo, autori, istituzione e link al protocollo. Tutto viene salvato automaticamente in questo browser — controlla l’indicatore in alto.'],
    model: ['Scegli il modello del flusso', 'Revisione nuova o aggiornata, con o senza altre fonti: queste scelte selezionano uno dei quattro modelli ufficiali PRISMA 2020 e mostrano solo i campi pertinenti.'],
    identification: ['Registra l’identificazione', 'Aggiungi ogni banca dati consultata (PubMed, Scopus…) con il numero di record; il totale viene sommato automaticamente. I registri di studi hanno un campo dedicato.'],
    removed: ['Rimuovi prima dello screening', 'Inserisci i duplicati e i record rimossi da strumenti di automazione o per altri motivi prima dello screening.'],
    screening: ['Screening e recupero', 'I record sottoposti a screening sono calcolati (identificati − rimossi). Inserisci gli esclusi allo screening e i report non recuperati; l’app ricava il resto e mostra ogni formula.'],
    eligibility: ['Valuta l’eleggibilità', 'Indica quanti report sono stati esclusi dopo la lettura del testo completo. I report valutati derivano dal calcolo precedente.'],
    reasons: ['Dettaglia i motivi di esclusione', 'Elenca ogni motivo con il suo conteggio. La somma deve corrispondere al totale dei report esclusi — la validazione ti avvisa se non è così.'],
    inclusion: ['Chiudi con l’inclusione', 'Inserisci i nuovi studi inclusi. Report e totali sono calcolati, sommando gli studi della versione precedente nelle revisioni aggiornate.'],
    diagram: ['Segui il diagramma in tempo reale', 'Il diagramma si aggiorna a ogni numero. Clicca su una casella per modificarne il campo, passa tra stile classico e moderno e usa lo zoom.'],
    node: ['Scopri l’origine di ogni valore', 'Qui trovi valore, origine (inserito o calcolato) e formula della casella selezionata. Per sovrascrivere un calcolo registra una giustificazione; note e provenienza restano documentate.'],
    validation: ['Correggi con la validazione', 'Ogni avviso spiega cosa è successo, perché conta e come risolvere. Clicca un avviso per andare direttamente al campo.'],
    toolbar: ['Usa la barra degli strumenti', 'Annulla e ripristina, zoom, schermo intero, stampa, cancella i dati e carica un esempio didattico — e riapri questo tour quando vuoi.'],
    checklist: ['Completa la checklist', 'Segui i 27 elementi PRISMA 2020: imposta lo stato, annota sezione e pagina del manoscritto e controlla l’avanzamento.'],
    export: ['Esporta per la pubblicazione', 'Genera PDF e SVG vettoriali, PNG, HTML interattivo, CSV/XLSX, un report e un pacchetto ZIP. Salva anche backup JSON del progetto.'],
    primi: ['Conosci Primi', 'Primi è l’assistente IA di PRISMA Lab: risponde su PRISMA 2020 e sui dati di questo progetto. Aprilo con questo pulsante.'],
    primiSetup: ['Collega il tuo provider IA', 'Scegli tra 15 provider — OpenAI, Anthropic, Gemini, DeepSeek, GLM, Qwen, Mistral e altri — o un modello locale con Ollama, usando la tua chiave. La chiave resta in questo browser e i dati vanno direttamente al provider, con il tuo consenso.'],
    primiFill: ['Lascia compilare Primi', 'Scrivi i tuoi numeri, ad es. “PubMed 320, Scopus 210, 85 duplicati”. Primi mostra una scheda con ogni campo (attuale → nuovo) e nulla cambia finché non clicchi Applica; un Annulla ripristina tutto. I campi calcolati seguono le formule.'],
    projects: ['Gestisci i tuoi progetti', 'In I miei progetti apri, duplichi, rinomini, importi ed elimini diagrammi. Tutto resta in questo browser — fai backup regolarmente.'],
    finish: ['Tutto pronto!', 'Hai percorso l’intero flusso di PRISMA Lab. Riapri questo tour quando vuoi con il pulsante Tour nella barra degli strumenti.'],
  },
  fr: {
    welcome: ['Bienvenue dans PRISMA Lab', 'Cette visite montre comment construire un diagramme PRISMA 2020 de bout en bout — des données du projet à l’export — et comment Primi, l’assistant IA, peut remplir les champs pour vous. Rien n’est modifié dans votre projet pendant la visite.'],
    project: ['Identifiez la revue', 'Commencez par le titre, les auteurs, l’institution et le lien du protocole. Tout est enregistré automatiquement dans ce navigateur — suivez l’indicateur en haut.'],
    model: ['Choisissez le modèle du flux', 'Revue nouvelle ou mise à jour, avec ou sans autres sources : ces choix sélectionnent l’un des quatre modèles officiels PRISMA 2020 et n’affichent que les champs pertinents.'],
    identification: ['Enregistrez l’identification', 'Ajoutez chaque base interrogée (PubMed, Scopus…) avec son nombre d’enregistrements ; le total est calculé automatiquement. Les registres d’études ont leur propre champ.'],
    removed: ['Retirez avant le tri', 'Indiquez les doublons et les enregistrements retirés par des outils d’automatisation ou pour d’autres raisons avant le tri.'],
    screening: ['Tri et récupération', 'Les enregistrements triés sont calculés (identifiés − retirés). Vous saisissez les exclusions au tri et les rapports non récupérés ; l’application déduit le reste et affiche chaque formule.'],
    eligibility: ['Évaluez l’éligibilité', 'Indiquez combien de rapports ont été exclus après lecture du texte intégral. Les rapports évalués proviennent du calcul précédent.'],
    reasons: ['Détaillez les motifs d’exclusion', 'Listez chaque motif avec son nombre. La somme doit correspondre au total des rapports exclus — la validation vous prévient sinon.'],
    inclusion: ['Terminez par l’inclusion', 'Indiquez les nouvelles études incluses. Rapports et totaux sont calculés, en ajoutant les études de la version précédente pour une revue mise à jour.'],
    diagram: ['Suivez le diagramme en direct', 'Le diagramme se met à jour à chaque chiffre. Cliquez sur une case pour modifier son champ, passez du style classique au moderne et utilisez le zoom.'],
    node: ['Voyez l’origine de chaque valeur', 'Vous voyez ici la valeur, l’origine (saisie ou calculée) et la formule de la case sélectionnée. Pour remplacer un calcul, indiquez une justification ; notes et provenance restent documentées.'],
    validation: ['Corrigez grâce à la validation', 'Chaque alerte explique ce qui s’est passé, pourquoi c’est important et comment corriger. Cliquez sur une alerte pour aller directement au champ.'],
    toolbar: ['Utilisez la barre d’outils', 'Annuler et rétablir, zoom, plein écran, impression, effacer les données et charger un exemple pédagogique — et relancer cette visite à tout moment.'],
    checklist: ['Complétez la checklist', 'Suivez les 27 éléments PRISMA 2020 : définissez le statut, notez la section et la page du manuscrit et suivez la progression.'],
    export: ['Exportez pour publication', 'Générez PDF et SVG vectoriels, PNG, HTML interactif, CSV/XLSX, un rapport et une archive ZIP. Enregistrez aussi des sauvegardes JSON du projet.'],
    primi: ['Découvrez Primi', 'Primi est l’assistant IA de PRISMA Lab : il répond sur PRISMA 2020 et sur les données de ce projet. Ouvrez-le avec ce bouton.'],
    primiSetup: ['Connectez votre fournisseur d’IA', 'Choisissez parmi 15 fournisseurs — OpenAI, Anthropic, Gemini, DeepSeek, GLM, Qwen, Mistral et d’autres — ou un modèle local avec Ollama, avec votre propre clé. Elle reste dans ce navigateur et les données vont directement au fournisseur, avec votre consentement.'],
    primiFill: ['Laissez Primi remplir', 'Saisissez vos chiffres, p. ex. « PubMed 320, Scopus 210, 85 doublons ». Primi affiche une carte avec chaque champ (actuel → nouveau) et rien ne change avant que vous cliquiez sur Appliquer ; un Annuler rétablit tout. Les champs calculés suivent leurs formules.'],
    projects: ['Gérez vos projets', 'Dans Mes projets, vous ouvrez, dupliquez, renommez, importez et supprimez des diagrammes. Tout reste dans ce navigateur — faites des sauvegardes régulièrement.'],
    finish: ['C’est prêt !', 'Vous avez parcouru tout le parcours de PRISMA Lab. Relancez cette visite quand vous voulez avec le bouton Visite de la barre d’outils.'],
  },
  de: {
    welcome: ['Willkommen bei PRISMA Lab', 'Diese Tour zeigt, wie Sie ein PRISMA-2020-Diagramm von Anfang bis Ende erstellen – von den Projektdaten bis zum Export – und wie Primi, der KI-Assistent, die Felder für Sie ausfüllen kann. Ihr Projekt wird während der Tour nicht verändert.'],
    project: ['Beschreiben Sie die Übersichtsarbeit', 'Beginnen Sie mit Titel, Autor:innen, Institution und Protokoll-Link. Alles wird automatisch in diesem Browser gespeichert – achten Sie auf die Anzeige oben.'],
    model: ['Wählen Sie das Flussmodell', 'Neue oder aktualisierte Übersichtsarbeit, mit oder ohne weitere Quellen: Diese Auswahl bestimmt eine der vier offiziellen PRISMA-2020-Vorlagen und zeigt nur passende Felder.'],
    identification: ['Erfassen Sie die Identifikation', 'Fügen Sie jede durchsuchte Datenbank (PubMed, Scopus …) mit ihrer Trefferzahl hinzu; die Summe wird automatisch gebildet. Studienregister haben ein eigenes Feld.'],
    removed: ['Vor dem Screening entfernen', 'Geben Sie Duplikate und Datensätze an, die vor dem Screening durch Automatisierung oder aus anderen Gründen entfernt wurden.'],
    screening: ['Screening und Beschaffung', 'Die gescreenten Datensätze werden berechnet (identifiziert − entfernt). Sie tragen im Screening Ausgeschlossene und nicht beschaffte Berichte ein; den Rest leitet die App ab und zeigt jede Formel.'],
    eligibility: ['Eignung prüfen', 'Geben Sie an, wie viele Berichte nach Volltextlektüre ausgeschlossen wurden. Die geprüften Berichte stammen aus der vorherigen Berechnung.'],
    reasons: ['Ausschlussgründe angeben', 'Listen Sie jeden Grund mit seiner Anzahl auf. Die Summe muss der Zahl ausgeschlossener Berichte entsprechen – die Validierung warnt sonst.'],
    inclusion: ['Mit dem Einschluss abschließen', 'Geben Sie die neu eingeschlossenen Studien an. Berichte und Summen werden berechnet und bei Aktualisierungen um Studien der Vorversion ergänzt.'],
    diagram: ['Diagramm live verfolgen', 'Das Flussdiagramm aktualisiert sich mit jeder Zahl. Klicken Sie auf ein Feld, um es zu bearbeiten, wechseln Sie zwischen klassischem und modernem Stil und nutzen Sie den Zoom.'],
    node: ['Herkunft jedes Werts sehen', 'Hier sehen Sie Wert, Herkunft (eingegeben oder berechnet) und Formel des gewählten Felds. Um eine Berechnung zu überschreiben, geben Sie eine Begründung an; Notizen und Herkunft bleiben dokumentiert.'],
    validation: ['Mit der Validierung korrigieren', 'Jeder Hinweis erklärt, was passiert ist, warum es wichtig ist und wie Sie es beheben. Ein Klick führt direkt zum betroffenen Feld.'],
    toolbar: ['Die Werkzeugleiste nutzen', 'Rückgängig und Wiederholen, Zoom, Vollbild, Drucken, Daten löschen und ein Lehrbeispiel laden – und diese Tour jederzeit erneut öffnen.'],
    checklist: ['Checkliste ausfüllen', 'Verfolgen Sie die 27 PRISMA-2020-Punkte: Status setzen, Abschnitt und Seite im Manuskript notieren und den Fortschritt sehen.'],
    export: ['Für die Veröffentlichung exportieren', 'Erzeugen Sie Vektor-PDF und -SVG, PNG, interaktives HTML, CSV/XLSX, einen Bericht und ein ZIP-Paket. Speichern Sie auch JSON-Sicherungen des Projekts.'],
    primi: ['Primi kennenlernen', 'Primi ist der KI-Assistent von PRISMA Lab: Er beantwortet Fragen zu PRISMA 2020 und zu den Daten dieses Projekts. Öffnen Sie ihn mit dieser Schaltfläche.'],
    primiSetup: ['KI-Anbieter verbinden', 'Wählen Sie aus 15 Anbietern – OpenAI, Anthropic, Gemini, DeepSeek, GLM, Qwen, Mistral und mehr – oder ein lokales Modell mit Ollama, mit Ihrem eigenen Schlüssel. Er bleibt in diesem Browser, und die Daten gehen mit Ihrer Zustimmung direkt an den Anbieter.'],
    primiFill: ['Primi ausfüllen lassen', 'Schreiben Sie Ihre Zahlen, z. B. „PubMed 320, Scopus 210, 85 Duplikate“. Primi zeigt eine Karte mit jedem Feld (aktuell → neu), und nichts ändert sich, bevor Sie auf Übernehmen klicken; ein Rückgängig macht alles ungeschehen. Berechnete Felder folgen ihren Formeln.'],
    projects: ['Projekte verwalten', 'Unter Meine Projekte öffnen, duplizieren, benennen, importieren und löschen Sie Diagramme. Alles bleibt in diesem Browser – sichern Sie regelmäßig.'],
    finish: ['Alles bereit!', 'Sie haben den gesamten Ablauf von PRISMA Lab kennengelernt. Öffnen Sie diese Tour jederzeit über die Schaltfläche Tour in der Werkzeugleiste.'],
  },
  'zh-CN': {
    welcome: ['欢迎使用 PRISMA Lab', '本导览将演示如何从头到尾完成一张 PRISMA 2020 流程图——从项目数据到导出——以及 AI 助手 Primi 如何帮您填写字段。导览过程中不会修改您的项目。'],
    project: ['填写综述信息', '先填写标题、作者、机构和方案链接。所有内容都会自动保存在本浏览器中——请留意顶部的保存状态。'],
    model: ['选择流程模板', '新综述或更新综述、是否使用其他来源：这些选项会对应 PRISMA 2020 的四种官方模板，并只显示适用的字段。'],
    identification: ['记录检索识别', '逐一添加检索过的数据库（PubMed、Scopus……）及记录数，系统会自动求和。研究注册库有单独的字段。'],
    removed: ['筛选前移除', '填写筛选前移除的重复记录，以及被自动化工具或其他原因移除的记录。'],
    screening: ['筛选与获取', '筛选记录数由系统计算（识别数 − 移除数）。您只需填写筛选排除数和未获取的报告数，其余由应用推导并显示公式。'],
    eligibility: ['评估合格性', '填写阅读全文后排除的报告数。评估的报告数来自上一步计算。'],
    reasons: ['列出排除理由', '逐条填写排除理由及数量。合计必须等于排除报告总数——不一致时验证会提示。'],
    inclusion: ['完成纳入', '填写新纳入的研究数。报告数和总数由系统计算；更新综述会加上上一版本的研究。'],
    diagram: ['实时查看流程图', '每输入一个数字，流程图都会更新。点击方框可编辑对应字段，也可切换经典与现代样式并缩放。'],
    node: ['查看每个数值的来源', '这里显示所选方框的数值、来源（输入或计算）及公式。如需覆盖计算值，请填写理由；备注与出处都会被记录。'],
    validation: ['借助验证修正', '每条提示都会说明发生了什么、为何重要以及如何修正。点击提示即可跳转到相关字段。'],
    toolbar: ['使用工具栏', '撤销与重做、缩放、全屏、打印、清空数据、加载教学示例——也可以随时重新打开本导览。'],
    checklist: ['完成核对清单', '跟踪 PRISMA 2020 的 27 个条目：设置状态、记录稿件中的章节和页码，并查看各部分进度。'],
    export: ['导出用于发表', '生成矢量 PDF 和 SVG、PNG、交互式 HTML、CSV/XLSX、报告和 ZIP 包，并保存项目的 JSON 备份。'],
    primi: ['认识 Primi', 'Primi 是 PRISMA Lab 的 AI 助手，可回答关于 PRISMA 2020 和本项目数据的问题。点击此按钮打开。'],
    primiSetup: ['连接 AI 服务商', '可在 15 家服务商中选择——OpenAI、Anthropic、Gemini、DeepSeek、GLM、Qwen、Mistral 等——或使用 Ollama 本地模型，并使用您自己的密钥。密钥只保存在本浏览器，数据在您同意后直接发送给服务商。'],
    primiFill: ['让 Primi 帮您填写', '输入您的数字，例如“PubMed 320、Scopus 210、重复 85”。Primi 会显示逐项修改卡片（当前 → 新值），在您点击“应用”前不会有任何改动；一次撤销即可全部还原。计算字段仍遵循公式。'],
    projects: ['管理您的项目', '在“我的项目”中可以打开、复制、重命名、导入和删除流程图。所有数据都保存在本浏览器中——请定期备份。'],
    finish: ['一切就绪！', '您已了解 PRISMA Lab 的完整流程。随时可通过工具栏中的“导览”按钮重新打开本导览。'],
  },
};
